using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using PJDev.DevelopKit.Framework.StatSystem.Runtime;
using UnityEditor;

namespace PJDev.DevelopKit.Framework.Editors.StatSystem
{
    internal static class StatEnumScriptGenerator
    {
        public const string GeneratedEnumPath =
            "Assets/Framework/Runtime/StatSystem/Generated/GameStat.cs";

        public const string GeneratedEnumName = "GameStat";

        public const string GeneratedEnumNamespace =
            "PJDev.DevelopKit.Framework.StatSystem.Runtime";

        public static string GeneratedEnumFullName =>
            $"{GeneratedEnumNamespace}.{GeneratedEnumName}";

        private static readonly HashSet<string> Keywords = new(StringComparer.Ordinal)
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch",
            "char", "checked", "class", "const", "continue", "decimal", "default",
            "delegate", "do", "double", "else", "enum", "event", "explicit", "extern",
            "false", "finally", "fixed", "float", "for", "foreach", "goto", "if",
            "implicit", "in", "int", "interface", "internal", "is", "lock", "long",
            "namespace", "new", "null", "object", "operator", "out", "override",
            "params", "private", "protected", "public", "readonly", "ref", "return",
            "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string",
            "struct", "switch", "this", "throw", "true", "try", "typeof", "uint",
            "ulong", "unchecked", "unsafe", "ushort", "using", "virtual", "void",
            "volatile", "while"
        };

        public static bool Generate(StatDatabaseSO database)
        {
            if (!TryBuild(database, out string code, out string error))
            {
                EditorUtility.DisplayDialog("Generate Stat Enum", error, "OK");
                return false;
            }

            if (!WriteIfChanged(GeneratedEnumPath, code))
                return false;

            AssetDatabase.Refresh();
            return true;
        }

        internal static bool TryBuild(
            StatDatabaseSO database,
            out string code,
            out string error)
        {
            code = null;
            error = null;

            if (database == null)
            {
                error = "Select a Stat Database first.";
                return false;
            }

            database.RebuildCache();
            IReadOnlyList<StatDefinition> definitions = database.Definitions;
            if (definitions.Count == 0)
            {
                error = "The selected database has no valid stats.";
                return false;
            }

            var members = new List<(string Name, string Value)>(definitions.Count);
            var usedNames = new HashSet<string>(StringComparer.Ordinal);
            for (int i = 0; i < definitions.Count; i++)
            {
                string value = definitions[i].Id.Value;
                string memberName = MakeIdentifier(value);
                if (!usedNames.Add(memberName))
                {
                    error =
                        $"Stat IDs produce the same enum member '{memberName}'. Rename one of the stats.";
                    return false;
                }

                members.Add((memberName, value));
            }

            code = BuildCode(members);
            return true;
        }

        private static string BuildCode(
            IReadOnlyList<(string Name, string Value)> members)
        {
            var builder = new StringBuilder(256 + members.Count * 64);
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("// Edit stats in Stat Database, then run Generate Enum.");
            builder.AppendLine();
            builder.Append("namespace ").AppendLine(GeneratedEnumNamespace);
            builder.AppendLine("{");
            builder.Append("    public enum ").AppendLine(GeneratedEnumName);
            builder.AppendLine("    {");

            for (int i = 0; i < members.Count; i++)
            {
                (string name, string value) = members[i];
                builder.Append("        [StatIdValue(\"")
                       .Append(EscapeString(value))
                       .AppendLine("\")]");
                builder.Append("        ").Append(name);
                if (i < members.Count - 1)
                    builder.Append(',');

                builder.AppendLine();
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static string MakeIdentifier(string value)
        {
            var builder = new StringBuilder(value.Length + 1);
            for (int i = 0; i < value.Length; i++)
            {
                char character = value[i];
                bool valid = i == 0
                    ? IsIdentifierStart(character)
                    : IsIdentifierPart(character);
                builder.Append(valid ? character : '_');
            }

            if (builder.Length == 0)
                builder.Append("Stat");
            else if (!IsIdentifierStart(builder[0]))
                builder.Insert(0, '_');

            string result = builder.ToString();
            return Keywords.Contains(result) ? "_" + result : result;
        }

        private static bool IsIdentifierStart(char value) =>
            value == '_' || char.IsLetter(value);

        private static bool IsIdentifierPart(char value) =>
            value == '_' || char.IsLetterOrDigit(value);

        private static string EscapeString(string value) =>
            value.Replace("\\", "\\\\").Replace("\"", "\\\"");

        private static bool WriteIfChanged(string assetPath, string content)
        {
            string fullPath = Path.GetFullPath(assetPath);
            string directory = Path.GetDirectoryName(fullPath);
            if (!string.IsNullOrEmpty(directory))
                Directory.CreateDirectory(directory);

            if (File.Exists(fullPath) &&
                string.Equals(File.ReadAllText(fullPath), content, StringComparison.Ordinal))
            {
                return false;
            }

            File.WriteAllText(fullPath, content, new UTF8Encoding(false));
            return true;
        }
    }
}
