using System.IO;
using System.Text;

namespace PJDev.DevelopKit.Framework.Editors.InventorySystem
{
    public static class InventoryEnumDefaultWriter
    {
        public static void WriteAllIfMissing()
        {
            RemoveLegacyGeneratedAssemblyDefinition();

            string root = InventoryEnumPaths.GeneratedRoot;
            string fullRoot = Path.GetFullPath(root);
            if (!Directory.Exists(fullRoot))
                Directory.CreateDirectory(fullRoot);

            WriteIfMissing(InventoryEnumPaths.ItemTypeAssetPath, BuildItemTypeSource());
            WriteIfMissing(InventoryEnumPaths.ContainerKindAssetPath, BuildContainerKindSource());
            WriteIfMissing(InventoryEnumPaths.CatalogAssetPath, BuildCatalogSource());
            WriteIfMissing(InventoryEnumPaths.RoutesAssetPath, BuildRoutesSource());
        }

        private static void RemoveLegacyGeneratedAssemblyDefinition()
        {
            DeleteIfExists(InventoryEnumPaths.LegacyGeneratedAssemblyAssetPath);
            DeleteIfExists(InventoryEnumPaths.LegacyGeneratedAssemblyAssetPath + ".meta");
        }

        private static void DeleteIfExists(string assetPath)
        {
            string fullPath = Path.GetFullPath(assetPath);
            if (!File.Exists(fullPath))
                return;

            File.Delete(fullPath);
        }

        private static void WriteIfMissing(string assetPath, string content)
        {
            string fullPath = Path.GetFullPath(assetPath);
            if (File.Exists(fullPath))
                return;

            string directory = Path.GetDirectoryName(fullPath);
            if (!string.IsNullOrEmpty(directory))
                Directory.CreateDirectory(directory);

            File.WriteAllText(fullPath, content, Encoding.UTF8);
        }

        private static string BuildItemTypeSource() =>
            "// <auto-generated />\n" +
            "// PJDev → Inventory → Generate Enums 로 갱신할 수 있습니다.\n\n" +
            "namespace PJDev.DevelopKit.Framework.InventorySystem.Runtime\n" +
            "{\n" +
            "    public enum ItemType\n" +
            "    {\n" +
            "        None = 0,\n" +
            "        General = 1,\n" +
            "        Consumable = 2,\n" +
            "        Equipment = 3,\n" +
            "        Material = 4,\n" +
            "        Quest = 5,\n" +
            "        Currency = 6\n" +
            "    }\n" +
            "}\n";

        private static string BuildContainerKindSource() =>
            "// <auto-generated />\n" +
            "// PJDev → Inventory → Generate Enums 로 갱신할 수 있습니다.\n\n" +
            "namespace PJDev.DevelopKit.Framework.InventorySystem.Runtime\n" +
            "{\n" +
            "    public enum ContainerKind\n" +
            "    {\n" +
            "        Main = 0,\n" +
            "        Equipment = 1,\n" +
            "        QuickBar = 2,\n" +
            "        Stash = 3,\n" +
            "        Quest = 4\n" +
            "    }\n" +
            "}\n";

        private static string BuildCatalogSource() =>
            "// <auto-generated />\n\n" +
            "using System;\n" +
            "using System.Collections.Generic;\n\n" +
            "namespace PJDev.DevelopKit.Framework.InventorySystem.Runtime\n" +
            "{\n" +
            "    public static class InventoryEnumCatalog\n" +
            "    {\n" +
            "        private static readonly ItemType[] ItemTypeOrder =\n" +
            "        {\n" +
            "            ItemType.None,\n" +
            "            ItemType.General,\n" +
            "            ItemType.Consumable,\n" +
            "            ItemType.Equipment,\n" +
            "            ItemType.Material,\n" +
            "            ItemType.Quest,\n" +
            "            ItemType.Currency,\n" +
            "        };\n\n" +
            "        private static readonly ContainerKind[] ContainerKindOrder =\n" +
            "        {\n" +
            "            ContainerKind.Main,\n" +
            "            ContainerKind.Equipment,\n" +
            "            ContainerKind.QuickBar,\n" +
            "            ContainerKind.Stash,\n" +
            "            ContainerKind.Quest,\n" +
            "        };\n\n" +
            "        private static readonly Dictionary<ItemType, string> ItemTypeDisplayNames = new()\n" +
            "        {\n" +
            "            { ItemType.None, \"None\" },\n" +
            "            { ItemType.General, \"General\" },\n" +
            "            { ItemType.Consumable, \"Consumable\" },\n" +
            "            { ItemType.Equipment, \"Equipment\" },\n" +
            "            { ItemType.Material, \"Material\" },\n" +
            "            { ItemType.Quest, \"Quest\" },\n" +
            "            { ItemType.Currency, \"Currency\" },\n" +
            "        };\n\n" +
            "        private static readonly Dictionary<ContainerKind, string> ContainerKindDisplayNames = new()\n" +
            "        {\n" +
            "            { ContainerKind.Main, \"Main\" },\n" +
            "            { ContainerKind.Equipment, \"Equipment\" },\n" +
            "            { ContainerKind.QuickBar, \"QuickBar\" },\n" +
            "            { ContainerKind.Stash, \"Stash\" },\n" +
            "            { ContainerKind.Quest, \"Quest\" },\n" +
            "        };\n\n" +
            "        public static IReadOnlyList<ItemType> ItemTypesInOrder => ItemTypeOrder;\n" +
            "        public static IReadOnlyList<ContainerKind> ContainerKindsInOrder => ContainerKindOrder;\n" +
            "        public static bool TryGetItemTypeDisplayName(ItemType value, out string displayName) =>\n" +
            "            ItemTypeDisplayNames.TryGetValue(value, out displayName);\n" +
            "        public static bool TryGetContainerKindDisplayName(ContainerKind value, out string displayName) =>\n" +
            "            ContainerKindDisplayNames.TryGetValue(value, out displayName);\n\n" +
            "        public static string GetItemTypeDisplayName(ItemType value) =>\n" +
            "            TryGetItemTypeDisplayName(value, out string displayName) ? displayName : value.ToString();\n\n" +
            "        public static string GetContainerKindDisplayName(ContainerKind value) =>\n" +
            "            TryGetContainerKindDisplayName(value, out string displayName) ? displayName : value.ToString();\n\n" +
            "        public static IEnumerable<ItemType> GetSelectableItemTypes()\n" +
            "        {\n" +
            "            IReadOnlyList<ItemType> order = ItemTypesInOrder;\n" +
            "            for (int i = 0; i < order.Count; i++)\n" +
            "            {\n" +
            "                ItemType itemType = order[i];\n" +
            "                if ((int)itemType != InventoryEnumCore.NoneItemTypeValue)\n" +
            "                    yield return itemType;\n" +
            "            }\n" +
            "        }\n\n" +
            "        public static IEnumerable<ItemType> GetAllItemTypes() => ItemTypesInOrder;\n\n" +
            "        public static IEnumerable<ContainerKind> GetAllContainerKinds() => ContainerKindsInOrder;\n" +
            "    }\n" +
            "}\n";

        private static string BuildRoutesSource() =>
            "// <auto-generated />\n\n" +
            "using System.Collections.Generic;\n\n" +
            "namespace PJDev.DevelopKit.Framework.InventorySystem.Runtime\n" +
            "{\n" +
            "    internal static class InventoryEnumRoutes\n" +
            "    {\n" +
            "        public static Dictionary<ItemType, ContainerKind[]> CreateItemTypeRouteTable()\n" +
            "        {\n" +
            "            var table = new Dictionary<ItemType, ContainerKind[]>();\n" +
            "            table[(ItemType)3] = new[] { (ContainerKind)1, (ContainerKind)0 };\n" +
            "            table[(ItemType)5] = new[] { (ContainerKind)4, (ContainerKind)0 };\n" +
            "            table[(ItemType)2] = new[] { (ContainerKind)2, (ContainerKind)0 };\n" +
            "            table[(ItemType)4] = new[] { (ContainerKind)0, (ContainerKind)3 };\n" +
            "            table[(ItemType)6] = new[] { (ContainerKind)0 };\n" +
            "            table[(ItemType)1] = new[] { (ContainerKind)0 };\n" +
            "            return table;\n" +
            "        }\n" +
            "    }\n" +
            "}\n";
    }
}
