using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using PJDev.DevelopKit.BasicTemplate.Runtime;
using UnityEditor;

namespace PJDev.DevelopKit.Framework.Editors.InventorySystem
{
    internal static class InventoryEnumScriptGenerator
    {
        private const string GeneratedRoot =
            "Assets/Framework/Runtime/InventorySystem/Runtime/Generated";

        private const string ItemTypePath = GeneratedRoot + "/ItemType.cs";
        private const string ContainerKindPath = GeneratedRoot + "/ContainerKind.cs";
        private const string CatalogPath = GeneratedRoot + "/InventoryEnumCatalog.Generated.cs";
        private const string RoutesPath = GeneratedRoot + "/InventoryEnumRoutes.Generated.cs";

        private static readonly HashSet<string> CSharpKeywords = new(StringComparer.Ordinal)
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
            "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
            "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
            "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
            "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
            "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
            "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
            "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
            "void", "volatile", "while"
        };

        [MenuItem("PJDev/Inventory/Generate Enums")]
        public static void GenerateFromMenu()
        {
            if (GenerateFromSettings())
                CDebug.Log("Inventory enum scripts generated.");
            else
                CDebug.Log("Inventory enum scripts are already up to date.");
        }

        public static bool GenerateFromSettings()
        {
            InventoryEnumsDocument document = InventoryEnumSettingsStore.LoadOrCreateDefault();
            if (!InventoryEnumSettingsStore.TryValidate(document, out string error))
            {
                EditorUtility.DisplayDialog("Generate Enums", error, "OK");
                return false;
            }

            InventoryEnumSettingsStore.Save(document);
            return Generate(document);
        }

        public static bool Generate(InventoryEnumsDocument document)
        {
            if (!InventoryEnumSettingsStore.TryValidate(document, out string error))
            {
                EditorUtility.DisplayDialog("Generate Enums", error, "OK");
                return false;
            }

            bool changed = false;
            changed |= WriteIfChanged(ItemTypePath, BuildEnumSource("ItemType", document.itemTypes));
            changed |= WriteIfChanged(ContainerKindPath, BuildEnumSource("ContainerKind", document.containerKinds));
            changed |= WriteIfChanged(CatalogPath, BuildCatalogSource(document));
            changed |= WriteIfChanged(RoutesPath, BuildRoutesSource(document));

            DeleteIfExists(GeneratedRoot + "/InventoryItemTypes.Generated.cs");
            DeleteIfExists(GeneratedRoot + "/InventoryKinds.Generated.cs");
            DeleteIfExists(GeneratedRoot + "/InventoryDefaultRoutes.Generated.cs");

            if (changed)
                AssetDatabase.Refresh();

            return changed;
        }

        public static bool TrySanitizeIdentifier(string raw, out string sanitized, out string error)
        {
            sanitized = null;
            error = null;

            if (string.IsNullOrWhiteSpace(raw))
            {
                error = "이름이 비어 있습니다.";
                return false;
            }

            sanitized = raw.Trim();
            if (char.IsDigit(sanitized[0]))
                sanitized = "_" + sanitized;

            for (int i = 0; i < sanitized.Length; i++)
            {
                char c = sanitized[i];
                if (char.IsLetterOrDigit(c) || c == '_')
                    continue;

                error = "이름은 영문, 숫자, _ 만 사용할 수 있습니다.";
                return false;
            }

            if (CSharpKeywords.Contains(sanitized))
            {
                error = $"'{sanitized}'는 C# 예약어입니다.";
                return false;
            }

            return true;
        }

        private static string BuildEnumSource(string enumName, InventoryEnumEntryData[] entries)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("// Inventory Data Editor → Enums 탭에서 편집 후 'Generate Enums'로 갱신합니다. 직접 수정하지 마세요.");
            builder.AppendLine();
            builder.AppendLine("namespace PJDev.DevelopKit.Framework.InventorySystem.Runtime");
            builder.AppendLine("{");
            builder.AppendLine($"    public enum {enumName}");
            builder.AppendLine("    {");

            for (int i = 0; i < entries.Length; i++)
            {
                InventoryEnumEntryData entry = entries[i];
                builder.Append($"        {entry.name} = {entry.value}");
                builder.AppendLine(i < entries.Length - 1 ? "," : string.Empty);
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static string BuildCatalogSource(InventoryEnumsDocument document)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("// Inventory Data Editor → Enums 탭에서 편집 후 'Generate Enums'로 갱신합니다. 직접 수정하지 마세요.");
            builder.AppendLine();
            builder.AppendLine("using System.Collections.Generic;");
            builder.AppendLine();
            builder.AppendLine("namespace PJDev.DevelopKit.Framework.InventorySystem.Runtime");
            builder.AppendLine("{");
            builder.AppendLine("    public static partial class InventoryEnumCatalog");
            builder.AppendLine("    {");

            AppendEnumOrder(builder, "ItemType", document.itemTypes);
            AppendEnumOrder(builder, "ContainerKind", document.containerKinds);
            AppendDisplayMap(builder, "ItemType", document.itemTypes);
            AppendDisplayMap(builder, "ContainerKind", document.containerKinds);

            builder.AppendLine("        public static IReadOnlyList<ItemType> ItemTypesInOrder => ItemTypeOrder;");
            builder.AppendLine();
            builder.AppendLine("        public static IReadOnlyList<ContainerKind> ContainerKindsInOrder => ContainerKindOrder;");
            builder.AppendLine();
            builder.AppendLine("        public static bool TryGetItemTypeDisplayName(ItemType value, out string displayName) =>");
            builder.AppendLine("            ItemTypeDisplayNames.TryGetValue(value, out displayName);");
            builder.AppendLine();
            builder.AppendLine("        public static bool TryGetContainerKindDisplayName(ContainerKind value, out string displayName) =>");
            builder.AppendLine("            ContainerKindDisplayNames.TryGetValue(value, out displayName);");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static string BuildRoutesSource(InventoryEnumsDocument document)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine();
            builder.AppendLine("using System.Collections.Generic;");
            builder.AppendLine();
            builder.AppendLine("namespace PJDev.DevelopKit.Framework.InventorySystem.Runtime");
            builder.AppendLine("{");
            builder.AppendLine("    internal static class InventoryEnumRoutes");
            builder.AppendLine("    {");
            builder.AppendLine("        public static Dictionary<ItemType, ContainerKind[]> CreateItemTypeRouteTable()");
            builder.AppendLine("        {");
            builder.AppendLine("            var table = new Dictionary<ItemType, ContainerKind[]>();");

            InventoryItemTypeRouteData[] routes = document.itemTypeRoutes ?? System.Array.Empty<InventoryItemTypeRouteData>();
            for (int i = 0; i < routes.Length; i++)
            {
                InventoryItemTypeRouteData route = routes[i];
                if (route?.containerKindValues == null || route.containerKindValues.Length == 0)
                    continue;

                var kindValues = new List<string>();
                for (int j = 0; j < route.containerKindValues.Length; j++)
                    kindValues.Add($"(ContainerKind){route.containerKindValues[j]}");

                builder.AppendLine(
                    $"            table[(ItemType){route.itemTypeValue}] = new[] {{ {string.Join(", ", kindValues)} }};");
            }

            builder.AppendLine("            return table;");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static void AppendEnumOrder(StringBuilder builder, string enumName, InventoryEnumEntryData[] entries)
        {
            builder.AppendLine($"        private static readonly {enumName}[] {enumName}Order =");
            builder.AppendLine("        {");

            for (int i = 0; i < entries.Length; i++)
                builder.AppendLine($"            {enumName}.{entries[i].name},");

            builder.AppendLine("        };");
            builder.AppendLine();
        }

        private static void AppendDisplayMap(StringBuilder builder, string enumName, InventoryEnumEntryData[] entries)
        {
            string mapName = enumName + "DisplayNames";
            builder.AppendLine($"        private static readonly Dictionary<{enumName}, string> {mapName} = new()");
            builder.AppendLine("        {");

            for (int i = 0; i < entries.Length; i++)
            {
                InventoryEnumEntryData entry = entries[i];
                string display = EscapeString(entry.displayName);
                builder.AppendLine($"            {{ {enumName}.{entry.name}, \"{display}\" }},");
            }

            builder.AppendLine("        };");
            builder.AppendLine();
        }

        private static string EscapeString(string value) =>
            (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");

        private static bool WriteIfChanged(string assetPath, string content)
        {
            string fullPath = Path.GetFullPath(assetPath);
            string directory = Path.GetDirectoryName(fullPath);
            if (!string.IsNullOrEmpty(directory))
                Directory.CreateDirectory(directory);

            if (File.Exists(fullPath))
            {
                string existing = File.ReadAllText(fullPath);
                if (string.Equals(existing, content, StringComparison.Ordinal))
                    return false;
            }

            File.WriteAllText(fullPath, content, Encoding.UTF8);
            return true;
        }

        private static void DeleteIfExists(string assetPath)
        {
            string fullPath = Path.GetFullPath(assetPath);
            if (!File.Exists(fullPath))
                return;

            File.Delete(fullPath);
            string metaPath = fullPath + ".meta";
            if (File.Exists(metaPath))
                File.Delete(metaPath);
        }
    }
}
