using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using PJDev.DevelopKit.BasicTemplate.Runtime;
using PJDev.DevelopKit.Editors;
using UnityEditor;

namespace PJDev.DevelopKit.Framework.Editors.InventorySystem
{
    internal static class InventoryEnumScriptGenerator
    {
        private static string GeneratedRoot => InventoryEnumPaths.GeneratedRoot;

        private static string ItemTypePath => InventoryEnumPaths.ItemTypeAssetPath;

        private static string ContainerKindPath => InventoryEnumPaths.ContainerKindAssetPath;

        private static string CatalogPath => InventoryEnumPaths.CatalogAssetPath;

        private static string RoutesPath => InventoryEnumPaths.RoutesAssetPath;

        private static readonly HashSet<string> CSharpKeywords = new(StringComparer.Ordinal)
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
            "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
            "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
            "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
            "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
            "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
            "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
            "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
            "void", "volatile", "while"
        };

        [MenuItem("PJDev/Inventory/Generate Enums", priority = PJDevMenuPriority.Inventory + 1)]
        public static void GenerateFromMenu()
        {
            if (GenerateFromSettings())
                CDebug.Log("Inventory enum scripts generated.");
            else
                CDebug.Log("Inventory enum scripts are already up to date.");
        }

        public static bool GenerateFromSettings()
        {
            InventoryEnumsDocument document = InventoryEnumSettingsStore.LoadOrCreateDefault();
            if (!InventoryEnumSettingsStore.TryValidate(document, out string error))
            {
                EditorUtility.DisplayDialog("Generate Enums", error, "OK");
                return false;
            }

            InventoryEnumSettingsStore.Save(document);
            return Generate(document);
        }

        public static bool Generate(InventoryEnumsDocument document)
        {
            if (!InventoryEnumSettingsStore.TryValidate(document, out string error))
            {
                EditorUtility.DisplayDialog("Generate Enums", error, "OK");
                return false;
            }

            bool changed = InventoryEnumAssemblyConfigurator.EnableGeneratedMode(addDefineSymbol: true);
            changed |= WriteIfChanged(ItemTypePath, BuildEnumSource("ItemType", document.itemTypes));
            changed |= WriteIfChanged(ContainerKindPath, BuildEnumSource("ContainerKind", document.containerKinds));
            changed |= WriteIfChanged(CatalogPath, BuildCatalogSource(document));
            changed |= WriteIfChanged(RoutesPath, BuildRoutesSource(document));

            DeleteIfExists(GeneratedRoot + "/InventoryItemTypes.Generated.cs");
            DeleteIfExists(GeneratedRoot + "/InventoryKinds.Generated.cs");
            DeleteIfExists(GeneratedRoot + "/InventoryDefaultRoutes.Generated.cs");

            if (changed)
                AssetDatabase.Refresh();

            return changed;
        }

        public static bool TrySanitizeIdentifier(string raw, out string sanitized, out string error)
        {
            sanitized = null;
            error = null;

            if (string.IsNullOrWhiteSpace(raw))
            {
                error = "이름이 비어 있습니다.";
                return false;
            }

            sanitized = raw.Trim();
            if (char.IsDigit(sanitized[0]))
                sanitized = "_" + sanitized;

            for (int i = 0; i < sanitized.Length; i++)
            {
                char c = sanitized[i];
                if (char.IsLetterOrDigit(c) || c == '_')
                    continue;

                error = "이름은 영문, 숫자, _ 만 사용할 수 있습니다.";
                return false;
            }

            if (CSharpKeywords.Contains(sanitized))
            {
                error = $"'{sanitized}'는 C# 예약어입니다.";
                return false;
            }

            return true;
        }

        private static string BuildEnumSource(string enumName, InventoryEnumEntryData[] entries)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("// Edit in Inventory Data Editor → Enums tab, then run 'Generate Enums'. Do not edit manually.");
            builder.AppendLine();
            builder.AppendLine("namespace PJDev.DevelopKit.Framework.InventorySystem.Runtime");
            builder.AppendLine("{");
            builder.AppendLine($"    public enum {enumName}");
            builder.AppendLine("    {");

            for (int i = 0; i < entries.Length; i++)
            {
                InventoryEnumEntryData entry = entries[i];
                WriteXmlSummary(builder, "        ", entry.description);
                builder.Append($"        {entry.name} = {entry.value}");
                builder.AppendLine(i < entries.Length - 1 ? "," : string.Empty);
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static string BuildCatalogSource(InventoryEnumsDocument document)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("// Edit in Inventory Data Editor → Enums tab, then run 'Generate Enums'. Do not edit manually.");
            builder.AppendLine();
            builder.AppendLine("using System;");
            builder.AppendLine("using System.Collections.Generic;");
            builder.AppendLine();
            builder.AppendLine("namespace PJDev.DevelopKit.Framework.InventorySystem.Runtime");
            builder.AppendLine("{");
            builder.AppendLine("    public static class InventoryEnumCatalog");
            builder.AppendLine("    {");

            AppendEnumOrder(builder, "ItemType", document.itemTypes);
            AppendEnumOrder(builder, "ContainerKind", document.containerKinds);
            AppendDisplayMap(builder, "ItemType", document.itemTypes);
            AppendDisplayMap(builder, "ContainerKind", document.containerKinds);
            AppendDescriptionMap(builder, "ItemType", document.itemTypes);
            AppendDescriptionMap(builder, "ContainerKind", document.containerKinds);

            builder.AppendLine("        public static IReadOnlyList<ItemType> ItemTypesInOrder => ItemTypeOrder;");
            builder.AppendLine();
            builder.AppendLine("        public static IReadOnlyList<ContainerKind> ContainerKindsInOrder => ContainerKindOrder;");
            builder.AppendLine();
            builder.AppendLine("        public static bool TryGetItemTypeDisplayName(ItemType value, out string displayName) =>");
            builder.AppendLine("            ItemTypeDisplayNames.TryGetValue(value, out displayName);");
            builder.AppendLine();
            builder.AppendLine("        public static bool TryGetContainerKindDisplayName(ContainerKind value, out string displayName) =>");
            builder.AppendLine("            ContainerKindDisplayNames.TryGetValue(value, out displayName);");
            builder.AppendLine();
            builder.AppendLine("        public static string GetItemTypeDisplayName(ItemType value) =>");
            builder.AppendLine("            TryGetItemTypeDisplayName(value, out string displayName) ? displayName : value.ToString();");
            builder.AppendLine();
            builder.AppendLine("        public static string GetContainerKindDisplayName(ContainerKind value) =>");
            builder.AppendLine("            TryGetContainerKindDisplayName(value, out string displayName) ? displayName : value.ToString();");
            builder.AppendLine();
            builder.AppendLine("        public static bool TryGetItemTypeDescription(ItemType value, out string description) =>");
            builder.AppendLine("            ItemTypeDescriptions.TryGetValue(value, out description);");
            builder.AppendLine();
            builder.AppendLine("        public static bool TryGetContainerKindDescription(ContainerKind value, out string description) =>");
            builder.AppendLine("            ContainerKindDescriptions.TryGetValue(value, out description);");
            builder.AppendLine();
            builder.AppendLine("        public static IEnumerable<ItemType> GetSelectableItemTypes()");
            builder.AppendLine("        {");
            builder.AppendLine("            IReadOnlyList<ItemType> order = ItemTypesInOrder;");
            builder.AppendLine("            for (int i = 0; i < order.Count; i++)");
            builder.AppendLine("            {");
            builder.AppendLine("                ItemType itemType = order[i];");
            builder.AppendLine("                if ((int)itemType != 0)");
            builder.AppendLine("                    yield return itemType;");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        public static IEnumerable<ItemType> GetAllItemTypes() => ItemTypesInOrder;");
            builder.AppendLine();
            builder.AppendLine("        public static IEnumerable<ContainerKind> GetAllContainerKinds() => ContainerKindsInOrder;");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static string BuildRoutesSource(InventoryEnumsDocument document)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine();
            builder.AppendLine("using System.Collections.Generic;");
            builder.AppendLine();
            builder.AppendLine("namespace PJDev.DevelopKit.Framework.InventorySystem.Runtime");
            builder.AppendLine("{");
            builder.AppendLine("    public static class InventoryEnumRoutes");
            builder.AppendLine("    {");
            builder.AppendLine("        public static Dictionary<ItemType, ContainerKind[]> CreateItemTypeRouteTable()");
            builder.AppendLine("        {");
            builder.AppendLine("            var table = new Dictionary<ItemType, ContainerKind[]>();");

            InventoryItemTypeRouteData[] routes = document.itemTypeRoutes ?? System.Array.Empty<InventoryItemTypeRouteData>();
            for (int i = 0; i < routes.Length; i++)
            {
                InventoryItemTypeRouteData route = routes[i];
                if (route?.containerKindValues == null || route.containerKindValues.Length == 0)
                    continue;

                var kindValues = new List<string>();
                for (int j = 0; j < route.containerKindValues.Length; j++)
                    kindValues.Add($"(ContainerKind){route.containerKindValues[j]}");

                builder.AppendLine(
                    $"            table[(ItemType){route.itemTypeValue}] = new[] {{ {string.Join(", ", kindValues)} }};");
            }

            builder.AppendLine("            return table;");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static void AppendEnumOrder(StringBuilder builder, string enumName, InventoryEnumEntryData[] entries)
        {
            builder.AppendLine($"        private static readonly {enumName}[] {enumName}Order =");
            builder.AppendLine("        {");

            for (int i = 0; i < entries.Length; i++)
                builder.AppendLine($"            {enumName}.{entries[i].name},");

            builder.AppendLine("        };");
            builder.AppendLine();
        }

        private static void AppendDisplayMap(StringBuilder builder, string enumName, InventoryEnumEntryData[] entries)
        {
            string mapName = enumName + "DisplayNames";
            builder.AppendLine($"        private static readonly Dictionary<{enumName}, string> {mapName} = new()");
            builder.AppendLine("        {");

            for (int i = 0; i < entries.Length; i++)
            {
                InventoryEnumEntryData entry = entries[i];
                string display = EscapeString(entry.name);
                builder.AppendLine($"            {{ {enumName}.{entry.name}, \"{display}\" }},");
            }

            builder.AppendLine("        };");
            builder.AppendLine();
        }

        private static void AppendDescriptionMap(StringBuilder builder, string enumName, InventoryEnumEntryData[] entries)
        {
            string mapName = enumName + "Descriptions";
            builder.AppendLine($"        private static readonly Dictionary<{enumName}, string> {mapName} = new()");
            builder.AppendLine("        {");

            for (int i = 0; i < entries.Length; i++)
            {
                InventoryEnumEntryData entry = entries[i];
                string description = EscapeString(entry.description);
                builder.AppendLine($"            {{ {enumName}.{entry.name}, \"{description}\" }},");
            }

            builder.AppendLine("        };");
            builder.AppendLine();
        }

        private static void WriteXmlSummary(StringBuilder output, string indent, string description)
        {
            if (string.IsNullOrWhiteSpace(description))
                return;

            output.AppendLine($"{indent}/// <summary>");
            output.AppendLine($"{indent}/// {EscapeXmlDoc(description)}");
            output.AppendLine($"{indent}/// </summary>");
        }

        private static string EscapeXmlDoc(string value)
        {
            if (string.IsNullOrEmpty(value))
                return string.Empty;

            return value
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;")
                .Replace("\"", "&quot;");
        }

        private static string EscapeString(string value) =>
            (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");

        private static bool WriteIfChanged(string assetPath, string content)
        {
            string fullPath = Path.GetFullPath(assetPath);
            string directory = Path.GetDirectoryName(fullPath);
            if (!string.IsNullOrEmpty(directory))
                Directory.CreateDirectory(directory);

            if (File.Exists(fullPath))
            {
                string existing = File.ReadAllText(fullPath);
                if (string.Equals(existing, content, StringComparison.Ordinal))
                    return false;
            }

            File.WriteAllText(fullPath, content, Encoding.UTF8);
            return true;
        }

        private static void DeleteIfExists(string assetPath)
        {
            string fullPath = Path.GetFullPath(assetPath);
            if (!File.Exists(fullPath))
                return;

            File.Delete(fullPath);
            string metaPath = fullPath + ".meta";
            if (File.Exists(metaPath))
                File.Delete(metaPath);
        }
    }
}
