using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using PJDev.DevelopKit.BasicTemplate.Runtime;
using PJDev.DevelopKit.Framework.GameplayTagSystem.Runtime;
using UnityEditor;

namespace PJDev.DevelopKit.Framework.Editors.GameplayTagSystem
{
    /// <summary>Tag Manager 태그 목록에서 <c>GameplayTag</c> 정적 접근자 C# 코드를 생성합니다.</summary>
    internal static class GameplayTagScriptGenerator
    {
        private const string OutputAssetPath =
            "Assets/Framework/Runtime/GameplayTagSystem/Generated/GameplayTags.Generated.cs";

        private const string LegacyOutputAssetPath =
            "Assets/Framework/Runtime/GameplayTagSystem/Runtime/Generated/GameplayTags.Generated.cs";

        private static readonly HashSet<string> CSharpKeywords = new(StringComparer.Ordinal)
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
            "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
            "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
            "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
            "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
            "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
            "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
            "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
            "void", "volatile", "while"
        };

        /// <summary>메뉴에서 태그 스크립트 생성을 실행합니다.</summary>
        [MenuItem("PJDev/Gameplay Tags/Generate Tag Scripts")]
        public static void GenerateFromMenu()
        {
            if (Generate())
                CDebug.Log(GameplayTagEditorLocalization.TagScriptGenerateSuccess);
            else
                CDebug.Log(GameplayTagEditorLocalization.TagScriptGenerateSkipped);
        }

        /// <summary>현재 태그 목록으로 생성 파일을 갱신합니다. 변경이 없으면 false를 반환합니다.</summary>
        public static bool Generate()        {
            GameplayTagManager.ReloadTags();
            DeleteIfExists(LegacyOutputAssetPath);

            Dictionary<string, string> tagsByName = new(StringComparer.Ordinal);
            foreach (GameplayTag tag in GameplayTagManager.GetAllTags())
            {
                if (tag.IsNone || string.IsNullOrEmpty(tag.Name))
                    continue;

                if (tag.Name.StartsWith("Test.", StringComparison.Ordinal) ||
                    string.Equals(tag.Name, "Test", StringComparison.Ordinal))
                {
                    continue;
                }

                tagsByName[tag.Name] = tag.Description;
            }

            string output = BuildSource(tagsByName);
            string fullPath = Path.GetFullPath(OutputAssetPath);
            string directory = Path.GetDirectoryName(fullPath);
            if (!string.IsNullOrEmpty(directory))
                Directory.CreateDirectory(directory);

            if (File.Exists(fullPath))
            {
                string existing = File.ReadAllText(fullPath);
                if (string.Equals(existing, output, StringComparison.Ordinal))
                    return false;
            }

            File.WriteAllText(fullPath, output, Encoding.UTF8);
            AssetDatabase.ImportAsset(OutputAssetPath);
            DeleteIfExists(LegacyOutputAssetPath);
            return true;
        }

        private static void DeleteIfExists(string assetPath)
        {
            if (!File.Exists(Path.GetFullPath(assetPath)))
                return;

            AssetDatabase.DeleteAsset(assetPath);
        }

        private static string BuildSource(IReadOnlyDictionary<string, string> tagsByName)
        {
            TagTreeNode root = new();
            foreach (KeyValuePair<string, string> entry in tagsByName.OrderBy(e => e.Key, StringComparer.Ordinal))
                root.Insert(entry.Key, entry.Value);

            StringBuilder body = new();
            HashSet<string> usedFieldNames = new(StringComparer.Ordinal);
            WriteTreeMembers(root, body, "        ", usedFieldNames, isRootLevel: true);

            StringBuilder source = new();
            source.AppendLine("// <auto-generated />");
            source.AppendLine("// Updated only when you click 'Generate Tag Scripts' in Tag Manager. Do not edit manually.");
            source.AppendLine("// PJDev → Gameplay Tags → Generate Tag Scripts");
            source.AppendLine();
            source.AppendLine("namespace PJDev.DevelopKit.Framework.GameplayTagSystem.Runtime");
            source.AppendLine("{");
            source.AppendLine("    public struct GameplayTags");
            source.AppendLine("    {");

            if (body.Length == 0)
            {
                source.AppendLine("        // No tags registered. Add tags in Tag Manager, then run 'Generate Tag Scripts'.");
            }
            else
            {
                source.Append(body);
                source.AppendLine();
                source.AppendLine("        private static GameplayTag ResolveGeneratedTag(ref GameplayTag cache, string tagName)");
                source.AppendLine("        {");
                source.AppendLine("            if (!cache.IsValid)");
                source.AppendLine("                cache = GameplayTagManager.RequestTag(tagName, logWarningIfNotFound: false);");
                source.AppendLine();
                source.AppendLine("            return cache;");
                source.AppendLine("        }");
            }

            source.AppendLine("    }");
            source.AppendLine("}");
            return source.ToString();
        }

        private static void WriteTreeMembers(
            TagTreeNode node,
            StringBuilder output,
            string indent,
            HashSet<string> usedFieldNames,
            bool isRootLevel)
        {
            foreach (TagTreeNode child in node.Children.Values.OrderBy(c => c.Segment, StringComparer.Ordinal))
            {
                if (child.Children.Count == 0)
                {
                    WriteTagProperty(output, indent, child.FullTagName, child.Description, child.Segment, usedFieldNames);
                    continue;
                }

                if (isRootLevel)
                {
                    WriteNestedClass(output, indent, child, usedFieldNames);
                    continue;
                }

                string flatName = child.FullTagName.Replace('.', '_');
                WriteTagProperty(output, indent, child.FullTagName, child.Description, flatName, usedFieldNames);
            }
        }

        private static void WriteNestedClass(
            StringBuilder output,
            string indent,
            TagTreeNode node,
            HashSet<string> usedFieldNames)
        {
            string className = ToTypeIdentifier(node.Segment);
            WriteXmlSummary(output, indent, node.FullTagName, node.Description, $"Tag group: {node.Segment}");
            output.AppendLine($"{indent}public static class {className}");
            output.AppendLine($"{indent}{{");

            if (!string.IsNullOrEmpty(node.FullTagName))
                WriteTagProperty(output, indent + "    ", node.FullTagName, node.Description, "Self", usedFieldNames);

            foreach (TagTreeNode child in node.Children.Values.OrderBy(c => c.Segment, StringComparer.Ordinal))
            {
                if (child.Children.Count == 0)
                {
                    WriteTagProperty(output, indent + "    ", child.FullTagName, child.Description, child.Segment, usedFieldNames);
                    continue;
                }

                string flatName = child.FullTagName.Replace('.', '_');
                WriteTagProperty(output, indent + "    ", child.FullTagName, child.Description, flatName, usedFieldNames);
            }

            output.AppendLine($"{indent}}}");
            output.AppendLine();
        }

        private static void WriteTagProperty(
            StringBuilder output,
            string indent,
            string tagName,
            string description,
            string memberName,
            HashSet<string> usedFieldNames)
        {
            string propertyName = ToMemberIdentifier(memberName);
            string fieldName = CreateUniqueFieldName(tagName, usedFieldNames);

            WriteXmlSummary(output, indent, tagName, description, null);
            output.AppendLine($"{indent}public static GameplayTag {propertyName} => ResolveGeneratedTag(ref {fieldName}, \"{tagName}\");");
            output.AppendLine($"{indent}private static GameplayTag {fieldName};");
            output.AppendLine();
        }

        private static void WriteXmlSummary(
            StringBuilder output,
            string indent,
            string tagName,
            string description,
            string titleOverride)
        {
            output.AppendLine($"{indent}/// <summary>");
            output.AppendLine($"{indent}/// {(titleOverride ?? $"Tag: {EscapeXmlDoc(tagName)}")}");

            if (!string.IsNullOrWhiteSpace(description))
                output.AppendLine($"{indent}/// <para>{EscapeXmlDoc(description)}</para>");

            output.AppendLine($"{indent}/// </summary>");
        }

        private static string EscapeXmlDoc(string value)
        {
            if (string.IsNullOrEmpty(value))
                return string.Empty;

            return value
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;")
                .Replace("\"", "&quot;");
        }

        private static string CreateUniqueFieldName(string tagName, HashSet<string> usedFieldNames)
        {
            string baseName = ToCamelCaseField(tagName);
            string candidate = baseName;
            int suffix = 1;

            while (!usedFieldNames.Add(candidate))
            {
                candidate = $"{baseName}{suffix}";
                suffix++;
            }

            return candidate;
        }

        private static string ToCamelCaseField(string tagName)
        {
            string[] parts = tagName.Split('.');
            if (parts.Length == 0)
                return "tag";

            StringBuilder builder = new(parts[0].ToLowerInvariant());
            for (int i = 1; i < parts.Length; i++)
            {
                if (parts[i].Length == 0)
                    continue;

                builder.Append(char.ToUpperInvariant(parts[i][0]));
                if (parts[i].Length > 1)
                    builder.Append(parts[i].Substring(1));
            }

            builder.Append("Tag");
            return SanitizeIdentifier(builder.ToString(), lowerFirst: true);
        }

        private static string ToMemberIdentifier(string segment)
        {
            if (string.IsNullOrEmpty(segment))
                return "Tag";

            return SanitizeIdentifier(segment, lowerFirst: false);
        }

        private static string ToTypeIdentifier(string segment)
        {
            return SanitizeIdentifier(segment, lowerFirst: false);
        }

        private static string SanitizeIdentifier(string value, bool lowerFirst)
        {
            if (string.IsNullOrEmpty(value))
                return "Tag";

            StringBuilder builder = new(value.Length);
            for (int i = 0; i < value.Length; i++)
            {
                char c = value[i];
                if (char.IsLetterOrDigit(c) || c == '_')
                    builder.Append(c);
                else
                    builder.Append('_');
            }

            string sanitized = builder.ToString();
            if (sanitized.Length == 0)
                sanitized = "Tag";

            if (char.IsDigit(sanitized[0]))
                sanitized = "_" + sanitized;

            if (lowerFirst && sanitized.Length > 0)
                sanitized = char.ToLowerInvariant(sanitized[0]) + sanitized.Substring(1);

            if (CSharpKeywords.Contains(sanitized))
                return "@" + sanitized;

            return sanitized;
        }

        private sealed class TagTreeNode
        {
            public string Segment;
            public string FullTagName;
            public string Description;
            public readonly Dictionary<string, TagTreeNode> Children = new(StringComparer.Ordinal);

            public void Insert(string tagName, string description)
            {
                string[] parts = tagName.Split('.');
                TagTreeNode current = this;

                for (int i = 0; i < parts.Length; i++)
                {
                    string part = parts[i];
                    if (!current.Children.TryGetValue(part, out TagTreeNode child))
                    {
                        child = new TagTreeNode { Segment = part };
                        current.Children.Add(part, child);
                    }

                    current = child;
                    if (i == parts.Length - 1)
                    {
                        current.FullTagName = tagName;
                        current.Description = description;
                    }
                }
            }
        }
    }
}
